### ISSUE TITLE
Leap Motion file for Ur5 arm controlling

### ISSUE THREAD

**Issue by stevensu1838** [TAMS-Group/tams_ur5_setup#9]
Hi team,
I am a PhD student from New Zealand and Frank Steinicke is my cosupervisor. Dennis asked me to come the this package and learn about how he controls the UR5 arm with Leap Motion. But I don't find the code for Leap Motion here and Dennis is on his parental leave till August. Can you please tell me where I can find the Leap Motion part for ur5 arm controlling? i am aware that your setting is different(you arm is mounted on the wall). But this deosn't matter for now. Thanks a lot. Cheers. 
BR
Steven Su

**Comment by v4hn** [comment]
Hey Steven,

as you know Dennis is not around and we don't really know what you are talking about or what Dennis/Frank told you.

> Can you please tell me where I can find the Leap Motion part for ur5 arm controlling?

As far as we know he did not use the Leap Motion for controlling the *arm*, but only the *gripper*.
He *probably* did this using the Windows driver for the Leap Motion and sent ROS messages via his Unity Bridge to operate the robot through our ROS setup.
I don't know whether he made the (few lines of) code for this demo public, but using the ROS interfaces this can be setup for sure.

I'll close this issue because it is not related to this repository in particular.
